spring:
  datasource:
    url: jdbc:mysql://172.25.254.40/insight_common?useUnicode=true&characterEncoding=utf-8&useSSL=false
    hikari:
      connection-init-sql: set names utf8mb4
    username: root
    password: root
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 20
      max-wait: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 172.25.254.40
    port: 6379
    password: root
    database: 1
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1
  rabbitmq:
    addresses: 172.25.254.40:5672
    username: root
    password: root
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
    publisher-confirms: false
    publisher-returns: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  configuration:
    map-underscore-to-camel-case: true
qiniu:
  accessKey: xxx
  secretKey: xxx
  bucket: xxx